import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Ma_Shan_Zheng,
  ZCOOL_QingKe_HuangYou,
  ZCOOL_XiaoWei,
} from "next/font/google";
import "../styles/index.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const maShanZheng = Ma_Shan_Zheng({
  weight: "400",
  variable: "--font-ma-shan-zheng",
  preload: false,
});

const zcoolQingKeHuangYou = ZCOOL_QingKe_HuangYou({
  weight: "400",
  variable: "--font-zcool-qingke-huangyou",
  preload: false,
});

const zcoolXiaoWei = ZCOOL_XiaoWei({
  weight: "400",
  variable: "--font-zcool-xiaowei",
  preload: false,
});

export const metadata: Metadata = {
  title: "SHUYING-SPACE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${maShanZheng.variable} ${zcoolQingKeHuangYou.variable} ${zcoolXiaoWei.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
