import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/index.css";
import { WebAppProviders } from "@/providers/root";
import React from "react";

const geistSans = localFont({
  src: [
    {
      path: "../../public/fonts/Geist-VariableFont_wght.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-geist-sans",
  display: "swap",
});

const geistMono = localFont({
  src: [
    {
      path: "../../public/fonts/GeistMono-VariableFont_wght.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-geist-mono",
  display: "swap",
});

const maShanZheng = localFont({
  src: [
    {
      path: "../../public/fonts/MaShanZheng-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-ma-shan-zheng",
  preload: false,
});

const zcoolQingKeHuangYou = localFont({
  src: [
    {
      path: "../../public/fonts/ZCOOLQingKeHuangYou-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-zcool-qingke-huangyou",
  preload: false,
});

const zcoolXiaoWei = localFont({
  src: [
    {
      path: "../../public/fonts/ZCOOLXiaoWei-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-zcool-xiaowei",
  preload: false,
});

export const metadata: Metadata = {
  title: "SHUYING-SPACE",
  description: "Generated by create next app",
};

const webappContexts: React.ReactElement[] = []

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${maShanZheng.variable} ${zcoolQingKeHuangYou.variable} ${zcoolXiaoWei.variable} antialiased`}
      >
        <WebAppProviders contexts={webappContexts}>
          {children}
        </WebAppProviders>
      </body>
    </html>
  );
}
